### ISSUE TITLE
[Symfony-toggle] Create DBAL Implementation Compiler pass

### ISSUE THREAD

**Issue by kpicaza** [pheature-flags/pheature-flags#172]
Epic: #97 Symfony Toggle
Package: https://github.com/pheature-flags/symfony-toggle

Description:

Create DBAL Implementation Compiler pass from existing PheatureFlagsExtension. And include the compiler pass in the extension class.

```php
<?php

        if ('dbal' === $driver) {
            $finder->addArgument(new Reference(Connection::class));
            $repository->addArgument(new Reference(Connection::class));
        }

```

**Comment by xserrat** [comment]
Checking our current configuration, I think we'll need to define connection details to register the `Connection` class in the container. Now, Symfony throws an exception due to there's no service called `Doctrine\DBAL\Connection` and if you try to define it, it throws a fatal error because the `Connection` class needs some configuration through the constructor :/

**Comment by kpicaza** [comment]
Yes, maybe not defining an exclusive connection for our library, but getting the Connection class identifier inside the container from config.

```yaml
pheature_flags:
   dbal:
     connection_id: 'my.connection.identifier'
```
 
```php
<?php

        if ('dbal' === $driver) {
            $connectionId = $config->dbal()->connectionId();
            $finder->addArgument(new Reference($connectionId));
            $repository->addArgument(new Reference($connectionId));
        }
```

or something like that?

This will allow the end-users to use their preferred DBAL connection.
